const data = {
  status: "success",
  items: [
    {
      id: 1,
      title: "Chaqueta impermeable",
      price: 55000,
      img: require("./img/img1.jpeg"),
      cantidad: 1,
    },
    {
      id: 2,
      title: "Camiseta polo",
      price: 20000,
      img: require("./img/img2.jpeg"),
      cantidad: 1,
    },
    {
      id: 3,
      title: "Casco de seguridad",
      price: 17000,
      img: require("./img/img3.jpeg"),
      cantidad: 1,
    },
    {
      id: 4,
      title: "Desinfectante",
      price: 20000,
      img: require("./img/img4.jpeg"),
      cantidad: 1,
    },
    {
      id: 5,
      title: "Botas",
      price: 79000,
      img: require("./img/img5.jpeg"),
      cantidad: 1,
    },
    {
      id: 6,
      title: "Botas de caucho",
      price: 95000,
      img: require("./img/img6.jpeg"),
      cantidad: 1,
    },
    {
      id: 7,
      title: "Kit control de derrames",
      price: 70000,
      img: require("./img/img7.jpeg"),
      cantidad: 1,
    },
    {
      id: 8,
      title: "Botas impermeable",
      price: 90000,
      img: require("./img/img8.jpeg"),
      cantidad: 1,
    },
    {
      id: 9,
      title: "Tapabocas N95",
      price: 3500,
      img: require("./img/img9.jpeg"),
      cantidad: 1,
    },
    {
      id: 10,
      title: "Chaleco de seguridad amarillo",
      price: 35000,
      img: require("./img/img10.jpeg"),
      cantidad: 1,
    },
    {
      id: 11,
      title: "Chaleco de seguridad rojo",
      price: 35000,
      img: require("./img/img11.jpeg"),
      cantidad: 1,
    },
    {
      id: 12,
      title: "Chaleco de seguridad naranja",
      price: 35000,
      img: require("./img/img12.jpeg"),
      cantidad: 1,
    },
    {
      id: 13,
      title: "Overol",
      price: 70000,
      img: require("./img/img13.jpeg"),
      cantidad: 1,
    },
    {
      id: 14,
      title: "Chaleco reflectivo",
      price: 35000,
      img: require("./img/img14.jpeg"),
      cantidad: 1,
    },
    {
      id: 15,
      title: "Cuello de protección",
      price: 5000,
      img: require("./img/img15.jpeg"),
      cantidad: 1,
    },
  ],
};

export default data;
